baseURL = "https://blog.vftl.site/"
title = "AI 布 知 道/AI Preach Not"
theme = "stack"
relativeURLs = true
canonifyURLs = false

# 多语言配置（使用标准目录结构）
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = false

[languages]
  [languages.zh]
    languageCode = "zh-cn"
    languageName = "中文"
    weight = 1
    title = "AI 布 知 道"
    contentDir = "content"
    [languages.zh.params]
      [languages.zh.params.comments]
        enabled = true
        provider = "twikoo"
        
        [languages.zh.params.comments.twikoo]
          envId = "https://twikoo.lucyfer81.workers.dev"
          lang = "zh-CN"
  
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2
    title = "AI Preach Not"
    contentDir = "content/en"
    [languages.en.params]
      [languages.en.params.comments]
        enabled = true
        provider = "twikoo"
        
        [languages.en.params.comments.twikoo]
          envId = "https://twikoo.lucyfer81.workers.dev"
          lang = "en"

[params]
  mainSections = ["posts"]
  ShowThemeToggle = true
  ShowPostDate = true
  ShowCodeCopyButtons = true
  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.comments]
    enabled = true
    provider = "twikoo"
    
    [params.comments.twikoo]
      envId = "https://twikoo.lucyfer81.workers.dev"

[server]
  bind = "0.0.0.0"

# 菜单配置 - 中文
[[languages.zh.menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10
[[languages.zh.menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20
[[languages.zh.menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30

# 菜单配置 - 英文
[[languages.en.menu.main]]
  identifier = "home"
  name = "Home"
  url = "/en/"
  weight = 10
[[languages.en.menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/en/posts/"
  weight = 20
[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 30
