baseURL = "https://my-ai-sandbox-90j.pages.dev/"
title = "AI 布 知 道/AI Preach Not"
theme = "stack"
relativeURLs = true
canonifyURLs = false

# 多语言配置（基于当前目录结构）
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh]
    languageCode = "zh-cn"
    languageName = "中文"
    weight = 1
    title = "AI 布 知 道"
  
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 2
    title = "AI Preach Not"

[params]
  mainSections = ["posts"]
  ShowThemeToggle = true
  ShowPostDate = true
  ShowCodeCopyButtons = true
  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"

[server]
  bind = "0.0.0.0"

# 菜单配置
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10
[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20
[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30