baseURL = "https://my-ai-sandbox-90j.pages.dev/"
languageCode = "zh-cn"
title = "AI 布 知 道/AI Preach Not"
theme = "stack"
relativeURLs = true
canonifyURLs = false

[params]
  mainSections = ["posts"]
  ShowThemeToggle = true  # 启用明暗主题切换
  ShowPostDate = true     # 显示文章日期
  # DateFormat = "2006年1月2日"  # 中文日期格式
  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04 MST"
  ShowCodeCopyButtons = true  # 代码块复制按钮，适合技术文章

[server]
  bind = "0.0.0.0"
  
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10
[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 20
[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30