name = "twikoo"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "TWIKOO_COMMENTS", id = "74a0ee7426974db8aff7044462f7ace3" }
]

[[d1_databases]]
binding = "DB"
database_name = "twikoo-db"
database_id = "ada85d47-b7a1-4745-b4a6-36814fb444d9"

[build]
command = "npx esbuild --bundle --platform=node --format=esm --define:process.env.BROWSER=true --main-fields=browser,module,main --external:canvas --outdir=dist src/index.js"
[vars]
TWIKOO_PATH = "/comment"
